/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.gradle.project;

public class SomeClass {
    public static int sum(int a, int b) {
        return a + b;
    }
}
